// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Rampfy.WebAPI.Data;

namespace Rampfy.WebAPI.Migrations
{
    [DbContext(typeof(DataContext))]
    partial class DataContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.0");

            modelBuilder.Entity("Rampfy.WebAPI.Models.Usuario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Codigo")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Email")
                        .HasColumnType("TEXT");

                    b.Property<string>("Senha")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Usuarios");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Codigo = 111,
                            Email = "email1@mail.com",
                            Senha = "senha1"
                        },
                        new
                        {
                            Id = 2,
                            Codigo = 222,
                            Email = "email2@mail.com",
                            Senha = "senha2"
                        },
                        new
                        {
                            Id = 3,
                            Codigo = 333,
                            Email = "email3@mail.com",
                            Senha = "senha3"
                        },
                        new
                        {
                            Id = 4,
                            Codigo = 444,
                            Email = "email4@mail.com",
                            Senha = "senha4"
                        },
                        new
                        {
                            Id = 5,
                            Codigo = 555,
                            Email = "email5@mail.com",
                            Senha = "senha5"
                        });
                });

            modelBuilder.Entity("Rampfy.WebAPI.Models.Venda", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Codigo")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("Data")
                        .HasColumnType("TEXT");

                    b.Property<double>("Valor")
                        .HasColumnType("REAL");

                    b.HasKey("Id");

                    b.ToTable("Vendas");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Codigo = 111,
                            Data = new DateTime(2023, 5, 5, 8, 18, 34, 993, DateTimeKind.Local).AddTicks(5560),
                            Valor = 10.5
                        },
                        new
                        {
                            Id = 2,
                            Codigo = 222,
                            Data = new DateTime(2023, 5, 5, 8, 18, 34, 997, DateTimeKind.Local).AddTicks(2258),
                            Valor = 11.5
                        },
                        new
                        {
                            Id = 3,
                            Codigo = 333,
                            Data = new DateTime(2023, 5, 6, 8, 18, 34, 997, DateTimeKind.Local).AddTicks(2278),
                            Valor = 12.5
                        },
                        new
                        {
                            Id = 4,
                            Codigo = 444,
                            Data = new DateTime(2023, 5, 7, 8, 18, 34, 997, DateTimeKind.Local).AddTicks(2281),
                            Valor = 13.5
                        },
                        new
                        {
                            Id = 5,
                            Codigo = 555,
                            Data = new DateTime(2023, 5, 8, 8, 18, 34, 997, DateTimeKind.Local).AddTicks(2283),
                            Valor = 14.5
                        },
                        new
                        {
                            Id = 6,
                            Codigo = 666,
                            Data = new DateTime(2023, 5, 9, 8, 18, 34, 997, DateTimeKind.Local).AddTicks(2296),
                            Valor = 15.5
                        },
                        new
                        {
                            Id = 7,
                            Codigo = 777,
                            Data = new DateTime(2023, 5, 10, 8, 18, 34, 997, DateTimeKind.Local).AddTicks(2298),
                            Valor = 16.5
                        },
                        new
                        {
                            Id = 8,
                            Codigo = 888,
                            Data = new DateTime(2023, 5, 11, 8, 18, 34, 997, DateTimeKind.Local).AddTicks(2303),
                            Valor = 17.5
                        },
                        new
                        {
                            Id = 9,
                            Codigo = 999,
                            Data = new DateTime(2023, 5, 12, 8, 18, 34, 997, DateTimeKind.Local).AddTicks(2305),
                            Valor = 18.5
                        },
                        new
                        {
                            Id = 10,
                            Codigo = 1111,
                            Data = new DateTime(2023, 5, 13, 8, 18, 34, 997, DateTimeKind.Local).AddTicks(2309),
                            Valor = 19.5
                        },
                        new
                        {
                            Id = 11,
                            Codigo = 2222,
                            Data = new DateTime(2023, 5, 14, 8, 18, 34, 997, DateTimeKind.Local).AddTicks(2311),
                            Valor = 20.5
                        },
                        new
                        {
                            Id = 12,
                            Codigo = 3333,
                            Data = new DateTime(2023, 5, 15, 8, 18, 34, 997, DateTimeKind.Local).AddTicks(2313),
                            Valor = 21.5
                        },
                        new
                        {
                            Id = 13,
                            Codigo = 4444,
                            Data = new DateTime(2023, 5, 16, 8, 18, 34, 997, DateTimeKind.Local).AddTicks(2315),
                            Valor = 22.5
                        },
                        new
                        {
                            Id = 14,
                            Codigo = 5555,
                            Data = new DateTime(2023, 5, 17, 8, 18, 34, 997, DateTimeKind.Local).AddTicks(2317),
                            Valor = 23.5
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
